[CLOSE_DEPLOYMENT_BUTTON_COLOR]
type = "i16"
value = [217, 67, 49]

[CLOSE_DEPLOYMENT_BUTTON_TOLERANCE]
type = "u16"
value = 25

[CLOSE_DEPLOYMENT_BUTTON_RED_PIXEL_THRESHOLD]
type = "f32"
value = 0.65

[OCR_PREPROCESS_BRIGHTNESS_THRESHOLD]
type = "u8"
value = 200

[OCR_PREPROCESS_MONOCHROMATICY_THRESHOLD]
type = "u16"
value = 3

[OCR_PREPROCESS_BRIGHTNESS_EDGE_THRESHOLD]
type = "u8"
value = 130

[OCR_PREPROCESS_SIMILARITY_EDGE_THRESHOLD]
type = "u16"
value = 48

[OCR_PREPROCESS_DILATE_RADIUS]
type = "u32"
value = 3

[ALPHA_MARKER_COLOR_HSV]
type = "u16"
value = [105, 100, 100]

[BRAVO_MARKER_COLOR_HSV]
type = "u16"
value = [285, 46, 85]

[CHARLIE_MARKER_COLOR_HSV]
type = "u16"
value = [158, 60, 91]

[FIND_MARKER_HSV_HUE_TOLERANCE]
type = "u16"
value = 15

[FIND_MARKER_HSV_SAT_TOLERANCE]
type = "u8"
value = 25

[FIND_MARKER_HSV_VIB_TOLERANCE]
type = "u8"
value = 25

[MAP_MARKER_POI_LOCATION]
type = "f32"
value = 0.70
